### ISSUE TITLE
no table: drug

### ISSUE THREAD

**Issue by alialmujab** [Mohammad-Hussain95/GNN_DDI#1]
Hello, can you help me with next error
the database not found (event.db) in repository
Execution failed on sql 'select * from drug;': no such table: drug

**Comment by Mohammad-Hussain95** [comment]
Hello Ali,
you can find this database (event.db) from this [GitHub link](https://github.com/YifanDengWHU/DDIMDL).

**Comment by alialmujab** [comment]
Thank you very much Hussain
Is it possible to get your email to call or WhatsApp number

‫في الجمعة، 6 يناير 2023 في 7:30 ص تمت كتابة ما يلي بواسطة ‪hussain‬‏ <‪
***@***.***‬‏>:‬
