### ISSUE TITLE
Conv_LSTM is not defined 

### ISSUE THREAD

**Issue by atomicKhalil** [Mohammad-Hussain95/GNN_DDI#3]
Hi there, I'd like to thank you for all your hard work on this project. I have managed to fix all the previous errors I encountered, but I've run into another problem in the train.py file. Specifically, when I try to create an instance of the Conv_LSTM class with dnn = Conv_LSTM(), I get a NameError that says 'Conv_LSTM' is not defined.

I suspect that this error might be due to a missing import statement or an incorrect class definition. Can you please provide some guidance on how I can fix this issue and successfully create an instance of the Conv_LSTM class? Thank you in advance for your help.

**Comment by Mohammad-Hussain95** [comment]
Hello, Thank you for your comment. 
Yes, I forget to replace that after testing the code. The code will work fine, if you replace Conv_LSTM() with DNN(), or delete those few lines.
I hope this will be helpful.
